packages:
  - packages/*
  - clients/*
  - services/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  sharp: set this to true or false

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - canvas
