export const LEG_FEE_RATE = .015
export const STRIPE_FEE_VAR = .0499
export const STRIPE_FEE_FIXED = 0.4
export const VAT = 1.22
export const FIRST_LEVEL_PARTNER_FEE_RATE = 0.005
export const SECOND_LEVEL_PARTNER_FEE_RATE = 0.0025
export const AREA_MANAGER_FEE_RATE = 0.0075
export const AREA_MANAGER_REGION_FEE_RATE = 0.001;
export const FEES_DISCLAIMER = 'Il prezzo è stato aumentato per includere le commissioni associate al pagamento in più rate.'
export const VERSION="3.9.5"
